name: somethings-todo production pull-request

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the production branch
  pull_request:
    branches: [production]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.14.0

      - name: Cache node_modules
        id: cache-node-modules-pre
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache
            node_modules
          key: ${{ runner.os }}-build-somethings-todo-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install node_modules
        if: steps.cache-node-modules-pre.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  check:
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache
            node_modules
          key: ${{ runner.os }}-build-somethings-todo-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Run linter
        run: yarn lint

      - name: Run unit tests
        run: yarn test:ci

      - name: Run e2e tests
        uses: cypress-io/github-action@v7
        with:
          start: yarn dev
          browser: chrome

  build:
    needs: [check]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache
            node_modules
          key: ${{ runner.os }}-build-somethings-todo-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Build somethings-todo project
        run: yarn build
